const params=new URLSearchParams(location.search),workflowId=params.get('workflowId');let state=null,annotations=[],documentText='';const stages=['specify','design','tasks','implement','review'];const $=id=>document.getElementById(id);const stageLabel=s=>({specify:'Specify',design:'Design',tasks:'Tasks',implement:'Implement',review:'Review'})[s]||s;const statusLabel=s=>({pending:'待开始',ready:'待执行',running:'Agent 执行中',waiting_approval:'等待人工确认',completed:'已完成',failed:'执行失败'})[s]||s;const esc=v=>String(v??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
async function load(){if(!workflowId){$('stage-title').textContent='缺少 workflowId';return}const [s,a,d]=await Promise.all([fetch(`/api/workflows/${encodeURIComponent(workflowId)}`).then(r=>r.json()),fetch(`/api/workflows/${encodeURIComponent(workflowId)}/annotations`).then(r=>r.json()),fetch(`/api/workflows/${encodeURIComponent(workflowId)}/document`).then(r=>r.json())]);state=s;annotations=a;documentText=d.content||'';render();}
function render(){ $('workflow-name').textContent=state.workflowId;$('timeline').innerHTML=stages.map((s,i)=>{const st=state.stages[s],cls=st.status==='completed'?'done':s===state.currentStage?'current':'';return `<div class="step ${cls}"><div class="dot">${st.status==='completed'?'✓':i+1}</div><div>${stageLabel(s)}</div></div>`}).join('');$('stage-card').innerHTML=`<div class="stage current"><strong>${stageLabel(state.currentStage)}</strong><small>${statusLabel(state.stages[state.currentStage].status)}</small></div>`;$('stage-list').innerHTML=stages.map(s=>{const st=state.stages[s];return `<div class="stage ${s===state.currentStage?'current':''} ${st.status==='completed'?'done':''}">${st.status==='completed'?'✓ ':''}${stageLabel(s)}<small>${statusLabel(st.status)}</small></div>`}).join('');$('stage-title').textContent=stageLabel(state.currentStage);$('stage-status').textContent=statusLabel(state.stages[state.currentStage].status);renderActions();renderDocument();renderAnnotations();}
function renderActions(){const st=state.stages[state.currentStage];$('actions').innerHTML=st.status==='waiting_approval'?'<button class="btn primary" onclick="decision(\'approve\')">通过并进入下一阶段</button><button class="btn warning" onclick="revise()">修改文档</button>':st.status==='failed'?'<button class="btn primary" onclick="decision(\'retry\')">重试</button>':'';}
function renderDocument(){$('document').innerHTML=documentText?`<div><span class="badge">${esc((state.stages[state.currentStage].artifact||'').split('/artifacts/')[1]||'artifact')}</span></div><p class="hint">可直接选择下方文字，再点击「标记选中内容」。</p><pre class="markdown" id="doc-text">${esc(documentText)}</pre><div style="margin-top:18px"><button class="btn" onclick="addAnnotation()">＋ 标记选中内容</button></div>`:'<div class="empty">当前阶段尚未生成文档</div>';}
function renderAnnotations(){$('annotations').innerHTML=annotations.length?annotations.map(a=>`<div class="annotation"><strong>${esc(a.type||'comment')}</strong><div>${esc(a.content||'')}</div>${a.target?.quote?`<small>选中：${esc(a.target.quote)}</small>`:''}<br><small>${esc(a.status||'open')}</small></div>`).join(''):'<div class="empty">还没有标记。</div>';}
function renderActivity(){$('activity').innerHTML=`<div class="empty">当前阶段：${stageLabel(state.currentStage)} · ${statusLabel(state.stages[state.currentStage].status)}</div>`;}
function connect(){const es=new EventSource(`/events?workflowId=${encodeURIComponent(workflowId)}`);es.onopen=()=>{$('connection').textContent='● Connected';$('connection').className='status ok'};es.onerror=()=>{$('connection').textContent='● Reconnecting';$('connection').className='status waiting'};es.addEventListener('annotation.created',e=>{annotations.push(JSON.parse(e.data).annotation);renderAnnotations()});es.addEventListener('workflow.updated',e=>{state=JSON.parse(e.data).state;load()});}
async function addAnnotation(){const sel=window.getSelection(),quote=sel?.toString()||'';const content=prompt(quote?`为选中的内容添加标记：\n「${quote}」`:'请输入需要 Agent 处理的标记：');if(!content)return;const type=prompt('标记类型（requirement / question / change / custom）：','custom')||'custom';const start=quote&&documentText.indexOf(quote);await fetch(`/api/workflows/${encodeURIComponent(workflowId)}/annotations`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,content,stage:state.currentStage,target:{quote,start:start<0?null:start,end:start<0?null:start+quote.length}})});sel?.removeAllRanges();}
async function decision(action){await fetch(`/api/workflows/${encodeURIComponent(workflowId)}/decisions`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,stage:state.currentStage})});}async function revise(){const feedback=prompt('请输入修改意见：');if(feedback)decision('revise:'+feedback)}
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.add('hidden'));b.classList.add('active');$(b.dataset.tab).classList.remove('hidden');if(b.dataset.tab==='activity')renderActivity()});load().then(connect);
